//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AviationSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class ATO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ATO()
        {
            this.DiplomaticPermits = new HashSet<DiplomaticPermit>();
            this.LandingPermits = new HashSet<LandingPermit>();
            this.LandingTakeoffPermits = new HashSet<LandingTakeoffPermit>();
            this.OverFlyPermits = new HashSet<OverFlyPermit>();
            this.OverFlyPermits1 = new HashSet<OverFlyPermit>();
            this.ScheduledFlights = new HashSet<ScheduledFlight>();
        }
    
        public int ATO_ID { get; set; }
        public string ATO_First_Name { get; set; }
        public string ATO_Last_Name { get; set; }
        public Nullable<System.DateTime> ATO_Shift_Starts { get; set; }
        public Nullable<System.DateTime> ATO_Shift_Ends { get; set; }
        public Nullable<System.DateTime> ATO_DOB { get; set; }
        public Nullable<int> ATO_Phone_Number { get; set; }
        public string ATO_Reg_ID { get; set; }
        public Nullable<int> ATO_Permits_Issued { get; set; }
        public string ATO_Username { get; set; }
        public string ATO_Password { get; set; }
        public int id { get; set; }
        public Nullable<int> AdminId { get; set; }
    
        public virtual Admin Admin { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DiplomaticPermit> DiplomaticPermits { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LandingPermit> LandingPermits { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LandingTakeoffPermit> LandingTakeoffPermits { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OverFlyPermit> OverFlyPermits { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OverFlyPermit> OverFlyPermits1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ScheduledFlight> ScheduledFlights { get; set; }
    }
}
