//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AviationSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class Emp_ATC
    {
        public int ATC_ID { get; set; }
        public string ATC_First_Name { get; set; }
        public string ATC_Last_Name { get; set; }
        public System.DateTime ATC_Shift_Starts { get; set; }
        public System.DateTime ATC_Shift_Ends { get; set; }
        public System.DateTime ATC_DOB { get; set; }
        public int ATC_Phone_Number { get; set; }
        public string ATC_Reg_ID { get; set; }
        public int ATC_Permits_Issued { get; set; }
        public string ATC_Username { get; set; }
        public string ATC_Password { get; set; }
    }
}
