//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AviationSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class LandingTakeoffPermit
    {
        public string LandingTakeoffID { get; set; }
        public string LandingTakeoffNo { get; set; }
        public string OperatorName { get; set; }
        public string AircraftType { get; set; }
        public string AircraftReg { get; set; }
        public string EntryPoint { get; set; }
        public string ExitPoint { get; set; }
        public Nullable<int> ATOid { get; set; }
        public Nullable<System.DateTime> ArrivalTime { get; set; }
        public Nullable<System.DateTime> TakeoffTime { get; set; }
        public string Purpose { get; set; }
    
        public virtual ATO ATO { get; set; }
    }
}
