//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AviationSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class ScheduledFlight
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ScheduledFlight()
        {
            this.ScheduledPermitDatas = new HashSet<ScheduledPermitData>();
        }
    
        public int Id { get; set; }
        public Nullable<System.DateTime> StartsIn { get; set; }
        public Nullable<System.DateTime> EndsIn { get; set; }
        public Nullable<int> ATOid { get; set; }
        public string Regesteration { get; set; }
    
        public virtual ATO ATO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ScheduledPermitData> ScheduledPermitDatas { get; set; }
    }
}
