//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AviationSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class ScheduledPermitData
    {
        public string FlightNumber { get; set; }
        public string Route { get; set; }
        public int spdID { get; set; }
        public string EntryPoint { get; set; }
        public string ExitPoint { get; set; }
        public string DaysofOperate { get; set; }
        public Nullable<int> ScheduledPermitID { get; set; }
    
        public virtual ScheduledFlight ScheduledFlight { get; set; }
    }
}
